package com.atom.crud.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dep.dep_id
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    private Integer depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dep.dep_name
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    private String depName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dep.dep_id
     *
     * @return the value of tbl_dep.dep_id
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dep.dep_id
     *
     * @param depId the value for tbl_dep.dep_id
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dep.dep_name
     *
     * @return the value of tbl_dep.dep_name
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dep.dep_name
     *
     * @param depName the value for tbl_dep.dep_name
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }
}