package com.atom.crud.dao;

import com.atom.crud.bean.Department;
import com.atom.crud.bean.DepartmentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int deleteByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    Department selectByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dep
     *
     * @mbg.generated Mon Apr 23 17:42:36 CST 2018
     */
    int updateByPrimaryKey(Department record);
}